### ISSUE TITLE
Only call default build task if it exists

### ISSUE THREAD

**Issue by danez** [researchgate/gradle-release#144]
There might be multiprojects where the root projects does not contain code or a build task, but the release task is still calling the build task.

**Comment by madhead** [comment]
Faced the same issue. Even

```groovy
release {
    buildTasks = [''] // buildTasks = ['subproject:build']
}
```

does not help

**Comment by danez** [comment]
As a workaround you might be able to do 
```
release {
    buildTasks = []
}
```
for the project that does not contain sourcecode.

Does this work?

**Comment by madhead** [comment]
No, that doesn't help. I connected to the Gradle in debug and it looks like it first runs build with `['build']` and then with whatever I set in `release.buildTasks`. Maybe some problems with running forked build?

The problem is my project layout. I have top level project `A` who has two children `A1` and `A2` in corresponding subdirectories. Also, there is `gradle.properties` in project `A` who sets the version for all project.

When I put release plugin to subprojects (as recommended in the docs) then it cannot find properties file with version (it is one level upper). So, I put release plugin in project `A`:

```groovy
plugins {
    id 'net.researchgate.release' version '2.3.2'
}

release {
    buildTasks = []
}
```

This configuration works, but the release version is not built at all. What I need is:

```groovy
plugins {
    id 'net.researchgate.release' version '2.3.2'
}

release {
    buildTasks = ['A1:build', 'A2:build'] // buildTasks = [':A1:build', ':A2:build']
}
```

But that doesn't work too as it still tries to run `build` task. Now I have stub `build` task in main project that depends on subprojects...

**Comment by danez** [comment]
Ah now I got it.
When you run `gradle build` it works and builds A1 and A2?

**Comment by madhead** [comment]
Yes. When I run `./gradlew build` from the root (`A`) it builds both projects.

**Comment by madhead** [comment]
When I put release configuration in subprojects:

```groovy
plugins {
    id 'java'
    id 'net.researchgate.release' version '2.3.2'
}

release {
    versionPropertyFile = '../gradle.properties'
}
```

The build fails because first subproject increments version in properties and it became `-SNAPSHOT` and the second project's `release` task fails.

**Comment by madhead** [comment]
And the final blocker. Even if I use separate `gradle.properties` for both subprojects and configure them independently, I get snapshot checking exception because second subproject (`A2`) depends on first (`A1`). And at the moment when `A2` is release `A1` is already bumped to snapshot:

```
* What went wrong:
Execution failed for task ':A2:checkSnapshotDependencies'.
> Snapshot dependencies detected: 
  	A2: [by.dev.madhead:a1:1.0.28-SNAPSHOT]
```

**Comment by madhead** [comment]
I've created a demo: https://github.com/madhead/gradle-release-demo:

```
┌[madhead@madhead-linux:~/Projects/gradle-release-demo]
└─$ ./gradlew release -Prelease.useAutomaticVersion=true
:release
:gradle-release-demo:createScmAdapter
:gradle-release-demo:initScmAdapter
:gradle-release-demo:checkCommitNeeded
:gradle-release-demo:checkUpdateNeeded
:gradle-release-demo:unSnapshotVersion
:gradle-release-demo:confirmReleaseVersion
:gradle-release-demo:checkSnapshotDependencies
:gradle-release-demo:runBuildTasks FAILED
:release FAILED
Release process failed, reverting back any changes made by Release Plugin.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'build' not found in root project 'gradle-release-demo'. Some candidates are: ':build'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.687 secs
```

**Comment by madhead** [comment]
Can you please check [this line](https://github.com/researchgate/gradle-release/blob/master/src/main/groovy/net/researchgate/release/ReleasePlugin.groovy#L77). Before project is evaluated `extension.buildTasks` contains default values, no matter what I set in `release` extension. Is that ok?

**Comment by danez** [comment]
I think there are more problems, because there are really a broad spectrum of different setup types. But you are right this line was wrong. I fixed it in master and created a snapshot, does it fix something for you? at least the `buildTasks = []` might work now i think.

```groovy
buildscript {
  repositories {
    maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local' }
  }

  dependencies {
    classpath 'net.researchgate:gradle-release:2.3.3-SNAPSHOT'
  }
}
```

**Comment by madhead** [comment]
Can you please check [this commit](https://github.com/madhead/gradle-release/commit/edc9377be336f47500da090427466202246f7378). When I tried a plugin with this "fix" it [looks ok](https://github.com/madhead/gradle-release-demo/tree/after-evaluate)

**Comment by danez** [comment]
:) Thanks I released 2.3.3 with this fix.

**Comment by Katona** [comment]
Hi,

The fix applied in 2.3.3 for this issue doesn't work for me. I still get `Task with name 'subproject:build' not found in root project 'parent'`. It seems that @madhead's patch is different than which actually got applied because that really seems to work. [Here](https://github.com/Katona/gradle-release/commit/a485a7fc8af28e5882a9843bfbac73826886f9c7)  I made the changes of @madhead to make it work. However, he uses `project.task()` which creates a task not retrieving it, which doesn't seem to be correct, yet it seems to work.

**Comment by madhead** [comment]
@Katona, like you've mentioned 2.3.3 has some extra changes, changing task access logic. And I faced the same problem as you. What I did is an extra task (in root project) project that depends on all the tasks needed for the release:

```groovy
release {
    buildTasks = ['releaseBuild']
}

task releaseBuild {
    dependsOn(
            'sps-reporting-bundle:clean',
            'sps-reporting-bundle:build',
            'sps-reporting-bundle:publish',
            'sps-reporting-test-utils:clean',
            'sps-reporting-test-utils:build',
            'sps-reporting-test-utils:publish'
    )
}
```

**Comment by Katona** [comment]
@madhead excellent, this is exactly what I came up with in seconds ago :)

**Comment by sadovnikov** [comment]
Here is an example of multi-project setup https://github.com/JV-ration/gradle-multi-project-sample, where any Gradle task fails, including `gradle tasks`. Problems disappear when declaration of release plugin is removed from top level `build.gradle`
```
plugins {
    id 'net.researchgate.release' version '2.3.4'
}
```

**Comment by franzbecker** [comment]
For people stumbling on this one: the example from @madhead works fine, but instead of explicitly listing all sub-projects you can simply do the following:
```
task releaseBuild {
	dependsOn subprojects.findResults { it.tasks.findByName('build') }
}
```

I even renamed the task at the root project to `build` so I didn't need to specify it as the `buildTask`:
```
task build {
	dependsOn subprojects.findResults { it.tasks.findByName('build') }
}
```

**Comment by myanything** [comment]
Any progress on this? 
1. I have cross-project dependency issue as listed in the issue, do we have a workaround?
2. Can we skip a subproject release if there is no code change?

Thank you!

**Comment by Hillkorn** [comment]
Hey, it depends on your gradle setup. The ones that should work can be found here
https://github.com/researchgate/gradle-release-examples

**Comment by gesellix** [comment]
Is there any workaround for "SNAPSHOT/project dependencies between subprojects" support?
