### ISSUE TITLE
When creating a release, SNAPSHOT version is deployed to nexus repo

### ISSUE THREAD

**Issue by Zlate87** [researchgate/gradle-release#98]
Hi,

##### What I need:
When creating a release, I need the artifact uploaded to nexus repo.

##### What I do:
I use createReleaseTag.dependsOn uploadArchives.

##### The problem I have:
If the version is set to 1.0.0-SNAPSHOT, when I start the release, it will ask if it should use version 1.0.0, I will confirm it and the release is performed and tag is created with 1.0.0 version set. However, when I check the nexus repo, the deployed files have version 1.0.0-SNAPSHOT (and are also deployed to the snapshot repo instead of the release repo).

I have tested with net.researchgate:gradle-release:2.0.2 on a windows machine with git. Has anyone else had the same problem?

**Comment by swpalmer** [comment]
Yes, I've hit that.  Here's a snippet of gradle code that I used to work
around it.  I use the 'maven-publish' plugin.

publishing {
publications {
maven(MavenPublication) {
//groupId  defaults to Project.getGroup()
//artifactId  defaults to Project.getName()

// The release plugin changes the version number we must account
// for that or it will be wrong when the publish happens.
// version defaults to Project.getVersion()

//from components.java

/* we don't set this in configuration phase because it will
   populate the filename and version with the values before the
   release plugin as removed the '-SNAPSHOT'
artifact distributionZip {
classifier 'dist'
}
artifact("${buildDir}/distributions/${project.name}-${project.version}.msi")
{
classifier 'installer'
}
*/
}
}
repositories {
maven {
url { "http://${repoHost}/libs-${project.version.endsWith('-SNAPSHOT') ?
'snapshot' : 'release' }-local" }
}
}
}


// Configure artifacts after the release plugin has tweaked version numbers
distributionZip << {
        // After distributionZip is created we know filenames won't change
and the version number is bumped
        publishing.publications.maven.version project.version
        publishing.publications.maven.artifacts.clear()
        publishing.publications.maven.artifact(distributionZip) {
classifier 'dist' }
        publishing.publications.maven.artifact("${buildDir}/distributions/${
project.name}-${project.version}.msi") {
                classifier 'installer'
        }
}
// Need to force this dependency since the main publishing block doesn't
// reference the artifact producing tasks in the configuration phase.
// (It is deferred to allow the release plugin to adjust the version number
//  e.g. by removing -SNAPSHOT or if the user enters a different number.)
publish.dependsOn distributionZip
publishToMavenLocal.dependsOn distributionZip

**Comment by danez** [comment]
@Zlate87 I just tested with a test repo and was not able to reproduce this behavior. You are not using the new maven-publish, right? May I ask how your build.gradle looks like and whats the output when doing a release?

@swpalmer The plugin indeed is not playing so well (or at all) with the new maven-publish, there is an other bug open for this issue.

**Comment by Zlate87** [comment]
I used the old "maven" plugin. I have the following files

build.gradle:

		buildscript {
		  /* Configure repositories. */
		  apply from: 'repositories.gradle'

		  /* Support for uploading artifacts to maven repository. */
		  apply from: 'maven.gradle'

		  dependencies {
			classpath 'com.android.tools.build:gradle:1.1.0'
			classpath 'net.researchgate:gradle-release:2.0.2'
		  }

		}

		apply from: 'release.gradle'
maven.gradle:

	  apply plugin: 'maven'
	  uploadArchives {
		configuration = configurations.archives
		repositories.mavenDeployer {

		  snapshotRepository(url: '[snapshot repo]') {
			authentication(userName: '[username]', password: '[password]')
		  }

		  repository(url: '[reelase repo]') {
			authentication(userName: '[username]', password: '[password]')
		  }

		  pom.project {
			groupId = project.group
			artifactId = project.artifact
			version = project.version
		  }
		}
release.gradle:

		apply plugin: 'net.researchgate.release'
		release {
		  tagPrefix = artifact
		}
		allprojects {
		  /* Attach the createReleaseTag task on modules where the maven plugin has been applied. */
		  if (tasks.findByPath('uploadArchives') != null) {
			createReleaseTag.dependsOn uploadArchives
		  }
		}

As an output I have several more gradle files. I add them like this:

	artifacts {
	  /* Plugin scripts. */
	  archives file: file('script1.gradle'), classifier: 'script1'
	  archives file: file('script2.gradle'), classifier: 'script2'
	}

**Comment by danez** [comment]
What is printed on the screen, while doing a release? The only thing I can think of is that the order of tasks is somehow screwing up. So the build task should happen immediately before the createReleaseTag-Task.

**Comment by Zlate87** [comment]
Here is the output when creating a release with version set to 0.4.11-SNAPSHOT in the gradle.properties file:

	C:\data\workspaces\android-gradle>gradle release
	:release                                                                                           
	:android-gradle:initScmPlugin
	:android-gradle:checkCommitNeeded                           
	:android-gradle:checkUpdateNeeded                           
	:android-gradle:unSnapshotVersion                           
	> Building 0% > :release > :android-gradle:confirmReleaseVersion
	??> This release version: [0.4.11]
	:android-gradle:confirmReleaseVersion
	:android-gradle:checkSnapshotDependencies                           
	:android-gradle:plugins/plugin1:compileJava UP-TO-DATE                
	:android-gradle:plugins/plugin1:compileGroovy UP-TO-DATE                                                                  
	:android-gradle:plugins/plugin1:processResources UP-TO-DATE                
	:android-gradle:plugins/plugin1:classes UP-TO-DATE                
	:android-gradle:plugins/plugin1:jar                           
	:android-gradle:plugins/plugin1:assemble                           
	:android-gradle:plugins/plugin1:compileTestJava UP-TO-DATE                
	:android-gradle:plugins/plugin1:compileTestGroovy UP-TO-DATE                                                                      
	:android-gradle:plugins/plugin1:processTestResources UP-TO-DATE                
	:android-gradle:plugins/plugin1:testClasses UP-TO-DATE                
	:android-gradle:plugins/plugin1:test UP-TO-DATE                                                                      
	:android-gradle:plugins/plugin1:check UP-TO-DATE                
	:android-gradle:plugins/plugin1:build                           
	:android-gradle:plugins/webdav:compileJava UP-TO-DATE                
	:android-gradle:plugins/webdav:compileGroovy UP-TO-DATE                                                                   
	:android-gradle:plugins/webdav:processResources UP-TO-DATE                
	:android-gradle:plugins/webdav:classes UP-TO-DATE                
	:android-gradle:plugins/webdav:jar                           
	:android-gradle:plugins/webdav:assemble                           
	:android-gradle:plugins/webdav:compileTestJava UP-TO-DATE                
	:android-gradle:plugins/webdav:compileTestGroovy UP-TO-DATE                                                                       
	:android-gradle:plugins/webdav:processTestResources UP-TO-DATE                
	:android-gradle:plugins/webdav:testClasses UP-TO-DATE                
	:android-gradle:plugins/webdav:test UP-TO-DATE                                                                       
	:android-gradle:plugins/webdav:check UP-TO-DATE                
	:android-gradle:plugins/webdav:build                           
	:android-gradle:preTagCommit                           
	:android-gradle:uploadArchives                           
	[ant:null] Error reading settings file 'C:\Users\user\AppData\Local\Temp\gradle_empty_settings8230110447286460046.xml' - ignoring. Error was: C:\Users\user\AppData\Local\Temp\gradle_empty_settings8230110447286460046.xml (The system cannot find the file
	specified)
	:android-gradle:build-scripts:uploadArchives                           
	Uploading: com/company/android/gradle/android-parent-gradle/0.4.11-SNAPSHOT/android-parent-gradle-0.4.11-SNAPSHOT-sonar-runner.gradle to repository remote at http://repo.company.com/nexus/content/repositories/internal-repository-snapshot
	Transferring 1K from remote                                            
	Uploaded 1K                                                            
	Uploading: com/company/android/gradle/android-parent-gradle/0.4.11-SNAPSHOT/android-parent-gradle-0.4.11-SNAPSHOT-repo-company-com.gradle to repository remote at http://repo.company.com/nexus/content/repositories/internal-repository-snapshot
	Transferring 0K from remote                                            
	Uploaded 0K                                                            
	Uploading: com/company/android/gradle/android-parent-gradle/0.4.11-SNAPSHOT/android-parent-gradle-0.4.11-SNAPSHOT-android-proguard.gradle to repository remote at http://repo.company.com/nexus/content/repositories/internal-repository-snapshot
	Transferring 2K from remote                                            
	Uploaded 2K                                                            
	Uploading: com/company/android/gradle/android-parent-gradle/0.4.11-SNAPSHOT/android-parent-gradle-0.4.11-SNAPSHOT-maven.gradle to repository remote at http://repo.company.com/nexus/content/repositories/internal-repository-snapshot
	Transferring 1K from remote                                            
	Uploaded 1K                                                            
	Uploading: com/company/android/gradle/android-parent-gradle/0.4.11-SNAPSHOT/android-parent-gradle-0.4.11-SNAPSHOT-android-library.gradle to repository remote at http://repo.company.com/nexus/content/repositories/internal-repository-snapshot
	Transferring 0K from remote                                            
	Uploaded 0K                                                            
	Uploading: com/company/android/gradle/android-parent-gradle/0.4.11-SNAPSHOT/android-parent-gradle-0.4.11-SNAPSHOT-android-application.gradle to repository remote at http://repo.company.com/nexus/content/repositories/internal-repository-snapshot
	Transferring 0K from remote                                            
	Uploaded 0K                                                            
	Uploading: com/company/android/gradle/android-parent-gradle/0.4.11-SNAPSHOT/android-parent-gradle-0.4.11-SNAPSHOT-release.gradle to repository remote at http://repo.company.com/nexus/content/repositories/internal-repository-snapshot
	Transferring 1K from remote                                            
	Uploaded 1K                                                            
	Uploading: com/company/android/gradle/android-parent-gradle/0.4.11-SNAPSHOT/android-parent-gradle-0.4.11-SNAPSHOT-plugin1.gradle to repository remote at http://repo.company.com/nexus/content/repositories/internal-repository-snapshot
	Transferring 0K from remote                                            
	Uploaded 0K                                                            
	Uploading: com/company/android/gradle/android-parent-gradle/0.4.11-SNAPSHOT/android-parent-gradle-0.4.11-SNAPSHOT-android.gradle to repository remote at http://repo.company.com/nexus/content/repositories/internal-repository-snapshot
	Transferring 3K from remote                                            
	Uploaded 3K                                                            
	Uploading: com/company/android/gradle/android-parent-gradle/0.4.11-SNAPSHOT/android-parent-gradle-0.4.11-SNAPSHOT-repositories.gradle to repository remote at http://repo.company.com/nexus/content/repositories/internal-repository-snapshot
	Transferring 1K from remote                                            
	Uploaded 1K                                                            
	:android-gradle:plugins/plugin1:uploadArchives                           
	Uploading: com/company/android/gradle/plugin1-gradle-plugin/0.4.11-SNAPSHOT/plugin1-gradle-plugin-0.4.11-20150401.122748-1.jar to repository remote at http://repo.company.com/nexus/content/repositories/internal-repository-snapshot
	Transferring 32K from remote                                           
	Uploaded 32K                                                           
	:android-gradle:plugins/webdav:uploadArchives                           
	Uploading: com/company/android/gradle/webdav-gradle-plugin/0.4.11-SNAPSHOT/webdav-gradle-plugin-0.4.11-20150401.122750-1.jar to repository remote at http://repo.company.com/nexus/content/repositories/internal-repository-snapshot
	Transferring 19K from remote                                            
	Uploaded 19K                                                            
	:android-gradle:createReleaseTag                                        
	> Building 0% > :release > :android-gradle:updateVersion
	??> Enter the next version (current one released as [0.4.11]): [0.4.12-SNAPSHOT]
	:android-gradle:updateVersion
	:android-gradle:commitNewVersion                           
							
	BUILD SUCCESSFUL
				   
	Total time: 1 mins 7.364 secs

In the tag, the right version is used (0.4.11), but when uploading to nexus, 0.4.11-SNAPSHOT is used

**Comment by mwhipple** [comment]
I'd think this is due to the version for `uploadArchives` being set during the configuration phase and not being updated after `unSnapshotVersion`.  I haven't used the old plugin by itself but I've had luck with things like:
```groovy
task refreshVersion << {
  uploadArchives.repositories.mavenDeployer.pom.version = version
}
uploadArchives.dependsOn refreshVersion
```

to make sure the version is updated during the execution phase.

**Comment by danez** [comment]
I think i already found a real solution inside the Plugin by running the build task in a separate process. All other stuff like publish, upload, etc can then be also attached to this subprocess which in fact has the correct version set already by gradle.properties.

I'm currently testing it in a separate branch.

**Comment by mwhipple** [comment]
Cool, I was actually thinking of that too but thought it may be more of an undertaking. If you hadn't already found it I'm fairly sure Gradle has something to handle kicking off nested builds as one of their less documented features (couldn't find the info quickly).

**Comment by danez** [comment]
This should be fixed in 2.1.0

**Comment by pstanoev** [comment]
I can confirm that this is fixed in 2.1.0 as long as the uploadArchives is added as you recommended: 
afterReleaseBuild.dependsOn uploadArchives

**Comment by RishikeshDarandale** [comment]
I still facing the same issue with latest version 2.3.5 while uploading the archives to maven repository. Here is the [sample project](https://github.com/RishikeshDarandale/gradle-examples/tree/master/sample-java-release)

I am executing following command:
```
gradle --debug clean release -Prelease.useAutomaticVersion=true
```

```
18:12:43.694 [INFO] [org.gradle.api.publication.maven.internal.action.LoggingMavenTransferListener] Downloading: sample/sample-java-release/1.0.0-SNAPSHOT/maven-metadata.xml from repository remote at file:///home/user/.m2/repository/
18:12:43.702 [ERROR] [org.gradle.api.publication.maven.internal.action.LoggingMavenTransferListener] Could not find metadata sample:sample-java-release:1.0.0-SNAPSHOT/maven-metadata.xml in remote (file:///home/user/.m2/repository)
18:12:43.715 [INFO] [org.gradle.api.publication.maven.internal.action.LoggingMavenTransferListener] Uploading: sample/sample-java-release/1.0.0-SNAPSHOT/sample-java-release-1.0.0-20160216.124243-1.jar to repository remote at file:///home/user/.m2/repository/
18:12:43.724 [INFO] [org.gradle.api.publication.maven.internal.action.LoggingMavenTransferListener] Transferring 1K from remote
18:12:43.726 [INFO] [org.gradle.api.publication.maven.internal.action.LoggingMavenTransferListener] Uploaded 1K
18:12:43.727 [INFO] [org.gradle.api.publication.maven.internal.action.LoggingMavenTransferListener] Uploading: sample/sample-java-release/1.0.0-SNAPSHOT/sample-java-release-1.0.0-20160216.124243-1.pom to repository remote at file:///home/user/.m2/repository/
18:12:43.727 [INFO] [org.gradle.api.publication.maven.internal.action.LoggingMavenTransferListener] Transferring 0K from remote
18:12:43.728 [INFO] [org.gradle.api.publication.maven.internal.action.LoggingMavenTransferListener] Uploaded 0K
18:12:43.736 [INFO] [org.gradle.api.publication.maven.internal.action.LoggingMavenTransferListener] Downloading: sample/sample-java-release/maven-metadata.xml from repository remote at file:///home/user/.m2/repository/
18:12:43.736 [ERROR] [org.gradle.api.publication.maven.internal.action.LoggingMavenTransferListener] Could not find metadata sample:sample-java-release/maven-metadata.xml in remote (file:///home/user/.m2/repository)
18:12:43.743 [INFO] [org.gradle.api.publication.maven.internal.action.LoggingMavenTransferListener] Uploading: sample/sample-java-release/1.0.0-SNAPSHOT/maven-metadata.xml to repository remote at file:///home/user/.m2/repository/
18:12:43.744 [INFO] [org.gradle.api.publication.maven.internal.action.LoggingMavenTransferListener] Transferring 0K from remote
18:12:43.745 [INFO] [org.gradle.api.publication.maven.internal.action.LoggingMavenTransferListener] Uploaded 0K
18:12:43.745 [INFO] [org.gradle.api.publication.maven.internal.action.LoggingMavenTransferListener] Uploading: sample/sample-java-release/maven-metadata.xml to repository remote at file:///home/user/.m2/repository/
18:12:43.745 [INFO] [org.gradle.api.publication.maven.internal.action.LoggingMavenTransferListener] Transferring 0K from remote
18:12:43.746 [INFO] [org.gradle.api.publication.maven.internal.action.LoggingMavenTransferListener] Uploaded 0K
18:12:43.747 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':uploadArchives'
```
and here the local repo details:
```
[~/projects/gradle-examples/sample-java-release] (master)
$ ll ~/.m2/repository/sample/sample-java-release/1.0.0-SNAPSHOT/
maven-metadata-remote.xml                             resolver-status.properties                            sample-java-release-1.0.0-20160216.124243-1.pom
maven-metadata.xml                                    sample-java-release-1.0.0-20160216.124243-1.jar       sample-java-release-1.0.0-20160216.124243-1.pom.md5
maven-metadata.xml.md5                                sample-java-release-1.0.0-20160216.124243-1.jar.md5   sample-java-release-1.0.0-20160216.124243-1.pom.sha1
maven-metadata.xml.sha1                               sample-java-release-1.0.0-20160216.124243-1.jar.sha1  
[~/projects/gradle-examples/sample-java-release] (master)
$ cat ~/.m2/repository/sample/sample-java-release/maven-metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>sample</groupId>
  <artifactId>sample-java-release</artifactId>
  <versioning>
    <versions>
      <version>1.0.0-SNAPSHOT</version>
    </versions>
    <lastUpdated>20160216124243</lastUpdated>
  </versioning>
</metadata>
[~/projects/gradle-examples/sample-java-release] (master)

```

**Comment by RishikeshDarandale** [comment]
Sorry, after moving the properties to gradle.properties, everything looks okay.

**Comment by asgarj** [comment]
For me, I had to remove version from build.gradle to gradle.properties, and add afterReleaseBuild.dependsOn(publish).
